### PR TITLE
mergify file

### PR DESCRIPTION
**Pull request by octonato**

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
LGTM!

**Comment by dwijnand** [comment]
My only questions were:
* why split the cleanup rule?
* why not have one "automatic merge on CI success" without base branch?

**Comment by octonato** [comment]
> why split the cleanup rule?

I discovered that if the label is not present, that action 'label' will fail and that will cause the branch to be marked as failed by GitHub. So we need to a condition to only remove the label if the label is present. 

And we want to clean-up a branch for every merged PR, also if it was merged manualy and doesn't have a label. So we new to split it otherwise we can't have the second case.

> why not have one "automatic merge on CI success" without base branch?

You are right, we don't need to have it per base branch. I will change it.

**Comment by dwijnand** [comment]
> I discovered that if the label is not present, that action 'label' will fail and that will cause the branch to be marked as failed by GitHub. So we need to a condition to only remove the label if the label is present.
> 
> And we want to clean-up a branch for every merged PR, also if it was merged manualy and doesn't have a label. So we new to split it otherwise we can't have the second case.

Makes sense.  Excellent.

**Pull request merged**
